/* Eigenständige Nutzungsbedingungen (live: /terms).
   Von Microsoft AppSource für die Add-in-Veröffentlichung verlangt.
   Entwurf/Mustertext — vor finalem Livegang juristisch prüfen lassen.
   Englisch zuerst (Zertifizierungsprüfer), Deutsch darunter. */

export const metadata = {
  title: 'Terms of Use — MailPilot',
  description: 'Terms of use for the MailPilot service and Outlook add-in.',
}

const EN = {
  title: 'Terms of Use',
  intro:
    'These terms govern your use of MailPilot — the website at mailpilot-ai.com and the MailPilot add-in for Microsoft Outlook (together, the "Service"), provided by Henrik Boye, Esinger Weg 65, 25436 Tornesch, Germany ("we", "us"). By using the Service you agree to these terms.',
  sections: [
    ['1. The service',
      'MailPilot is an AI assistant that turns your notes and bullet points into finished emails and can rephrase or translate them. The output is a suggestion you review and edit before use. We may improve, change or discontinue features over time.'],
    ['2. Account & eligibility',
      'Some features require an account, created and secured via our login provider. You are responsible for keeping your credentials safe and for all activity under your account. You must be at least 18 years old and provide accurate information.'],
    ['3. Acceptable use',
      'You agree not to use MailPilot to create unlawful, deceptive, harassing, hateful or infringing content, to spam, or to attempt to disrupt, reverse-engineer or gain unauthorised access to the Service. You are responsible for the content you enter and for the emails you ultimately send.'],
    ['4. Free tier, subscriptions & billing',
      'MailPilot offers a free daily quota and optional paid subscriptions. Paid plans are billed in advance (monthly or yearly) through our payment provider Stripe. You can manage, change or cancel your subscription at any time via the billing portal; cancellation takes effect at the end of the current billing period. Prices are shown before purchase and may change with notice for future periods.'],
    ['5. AI-generated content',
      'Emails are generated by an AI model and may contain errors or inaccuracies. You are solely responsible for reviewing, correcting and approving any content before sending it. We do not guarantee that generated content is accurate, complete or fit for a particular purpose, and we are not a party to the emails you send.'],
    ['6. Intellectual property',
      'The MailPilot software, brand and website are protected by intellectual property rights and remain ours. Subject to these terms, we grant you a limited, non-exclusive, non-transferable right to use the Service. Text you enter and the resulting emails remain yours.'],
    ['7. Disclaimer & limitation of liability',
      'The Service is provided "as is" without warranties of any kind to the extent permitted by law. We are liable without limitation for intent and gross negligence and under mandatory law (including the German Product Liability Act); for slight negligence we are liable only for breach of essential contractual obligations and limited to the foreseeable, typical damage. This does not exclude liability for injury to life, body or health.'],
    ['8. Term & termination',
      'You may stop using the Service and delete your account at any time. We may suspend or terminate access for breach of these terms or where required by law. Provisions that by their nature should survive (e.g. IP, liability) remain in effect after termination.'],
    ['9. Changes & governing law',
      'We may update these terms; we will post the new version here and, for material changes, give reasonable notice. German law applies, excluding its conflict-of-law rules and, where applicable, the UN Convention on Contracts for the International Sale of Goods. Mandatory consumer-protection rights of your country of residence remain unaffected. Contact: info@mailpilot-ai.com.'],
  ],
  note: 'Template text — please have it reviewed by a legal professional before going live. Last updated: June 2026.',
}

const DE = {
  title: 'Nutzungsbedingungen',
  intro:
    'Diese Bedingungen regeln deine Nutzung von MailPilot — der Website unter mailpilot-ai.com und des MailPilot-Add-ins für Microsoft Outlook (zusammen der „Dienst"), bereitgestellt von Henrik Boye, Esinger Weg 65, 25436 Tornesch, Deutschland („wir", „uns"). Mit der Nutzung des Dienstes stimmst du diesen Bedingungen zu.',
  sections: [
    ['1. Der Dienst',
      'MailPilot ist ein KI-Assistent, der aus deinen Notizen und Stichpunkten fertige E-Mails formuliert und diese umformulieren oder übersetzen kann. Das Ergebnis ist ein Vorschlag, den du vor der Verwendung prüfst und bearbeitest. Wir dürfen Funktionen weiterentwickeln, ändern oder einstellen.'],
    ['2. Konto & Voraussetzungen',
      'Einige Funktionen erfordern ein Konto, das über unseren Login-Anbieter erstellt und gesichert wird. Du bist für die Geheimhaltung deiner Zugangsdaten und für alle Aktivitäten unter deinem Konto verantwortlich. Du musst mindestens 18 Jahre alt sein und zutreffende Angaben machen.'],
    ['3. Zulässige Nutzung',
      'Du verpflichtest dich, MailPilot nicht für rechtswidrige, irreführende, belästigende, hetzerische oder rechtsverletzende Inhalte, für Spam oder für Versuche zu nutzen, den Dienst zu stören, zurückzuentwickeln oder unbefugt darauf zuzugreifen. Für die eingegebenen Inhalte und die letztlich versendeten E-Mails bist du verantwortlich.'],
    ['4. Gratis-Kontingent, Abos & Abrechnung',
      'MailPilot bietet ein tägliches Gratis-Kontingent und optionale kostenpflichtige Abos. Bezahlte Tarife werden im Voraus (monatlich oder jährlich) über unseren Zahlungsdienstleister Stripe abgerechnet. Du kannst dein Abo jederzeit über das Abrechnungsportal verwalten, ändern oder kündigen; die Kündigung wird zum Ende des laufenden Abrechnungszeitraums wirksam. Preise werden vor dem Kauf angezeigt und können für künftige Zeiträume mit Ankündigung angepasst werden.'],
    ['5. KI-generierte Inhalte',
      'E-Mails werden von einem KI-Modell erzeugt und können Fehler oder Ungenauigkeiten enthalten. Du bist allein dafür verantwortlich, Inhalte vor dem Versand zu prüfen, zu korrigieren und freizugeben. Wir übernehmen keine Gewähr dafür, dass erzeugte Inhalte richtig, vollständig oder für einen bestimmten Zweck geeignet sind, und sind nicht Partei der von dir versendeten E-Mails.'],
    ['6. Geistiges Eigentum',
      'Software, Marke und Website von MailPilot sind urheber-/schutzrechtlich geschützt und bleiben unser Eigentum. Im Rahmen dieser Bedingungen räumen wir dir ein einfaches, nicht übertragbares Recht zur Nutzung des Dienstes ein. Von dir eingegebene Texte und die daraus erzeugten E-Mails bleiben deine.'],
    ['7. Haftungsausschluss & -beschränkung',
      'Der Dienst wird im gesetzlich zulässigen Rahmen „wie besehen" ohne Gewährleistung bereitgestellt. Wir haften unbeschränkt für Vorsatz und grobe Fahrlässigkeit sowie nach zwingendem Recht (einschließlich Produkthaftungsgesetz); bei leichter Fahrlässigkeit haften wir nur für die Verletzung wesentlicher Vertragspflichten und der Höhe nach begrenzt auf den vorhersehbaren, typischen Schaden. Die Haftung für Schäden aus der Verletzung von Leben, Körper oder Gesundheit bleibt unberührt.'],
    ['8. Laufzeit & Beendigung',
      'Du kannst die Nutzung jederzeit beenden und dein Konto löschen. Wir dürfen den Zugang bei Verstoß gegen diese Bedingungen oder bei gesetzlicher Pflicht sperren oder beenden. Regelungen, die ihrer Natur nach fortgelten sollen (z. B. geistiges Eigentum, Haftung), bleiben nach Beendigung wirksam.'],
    ['9. Änderungen & anwendbares Recht',
      'Wir dürfen diese Bedingungen aktualisieren; die neue Fassung veröffentlichen wir hier und kündigen wesentliche Änderungen angemessen an. Es gilt deutsches Recht unter Ausschluss des Kollisionsrechts und – soweit anwendbar – des UN-Kaufrechts. Zwingende Verbraucherschutzrechte deines Wohnsitzlandes bleiben unberührt. Kontakt: info@mailpilot-ai.com.'],
  ],
  // Hinweis an Henrik (nicht öffentlich): Text bei Gelegenheit fachkundig prüfen lassen.
  note: 'Stand: Juni 2026.',
}

const S = {
  page: { maxWidth: 800, margin: '0 auto', padding: '48px 22px 80px', color: '#e7e2f3', fontFamily: 'Inter, Segoe UI, system-ui, sans-serif', lineHeight: 1.65 },
  brand: { fontSize: 14, color: '#a99fc0', marginBottom: 6 },
  h1: { fontSize: 30, fontWeight: 800, margin: '0 0 6px', color: '#f3f0fa' },
  intro: { fontSize: 16, color: '#c9bce8', margin: '0 0 30px' },
  h2: { fontSize: 18, fontWeight: 700, margin: '26px 0 8px', color: '#f3f0fa' },
  p: { fontSize: 15, margin: '0 0 14px' },
  note: { fontSize: 13, color: '#6e6388', borderTop: '1px solid #2c2148', paddingTop: 16, marginTop: 24 },
  hr: { border: 0, borderTop: '1px solid #2c2148', margin: '44px 0' },
  foot: { marginTop: 36, fontSize: 14, color: '#a99fc0' },
  a: { color: '#a78bfa' },
}

function Block({ d }) {
  return (
    <section>
      <h1 style={S.h1}>{d.title}</h1>
      <p style={S.intro}>{d.intro}</p>
      {d.sections.map(([h, b]) => (
        <div key={h}>
          <h2 style={S.h2}>{h}</h2>
          <p style={S.p}>{b}</p>
        </div>
      ))}
      <p style={S.note}>{d.note}</p>
    </section>
  )
}

export default function TermsPage() {
  return (
    <main style={S.page}>
      <div style={S.brand}>MailPilot · mailpilot-ai.com</div>
      <Block d={EN} />
      <hr style={S.hr} />
      <Block d={DE} />
      <p style={S.foot}><a style={S.a} href="/">← Back to MailPilot</a></p>
    </main>
  )
}
